yt:
  dlp:
    dlpPath: "D:\dlp\yt-dlp"
    locationFlag: "-P"
    location: "downloads"
    converterFlag: "--ffmpeg-location"
    converterLocation: "D:\dlp\ffmpeg\bin\ffmpeg.exe"
    extractFlag: "-x"
    formatFlag: "--audio-format"
