server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "yt"
    topics:
      ytdlp:
        name: "ytdlp"
        partitions: 1
        replicas: 1
yt:
  dlp:
    dlpPath: 'D:\dlp\yt-dlp'
    locationFlag: '-P'
    location: 'downloads'
    converterFlag: '--ffmpeg-location'
    converterLocation: 'D:\dlp\ffmpeg\bin\ffmpeg.exe'
    extractFlag: '-x'
    formatFlag: '--audio-format'
